name: Docker build (dry-run)

on:
  push:
    branches:
      - gh_actions

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Setup Docker Buildx
      run: docker/setup-buildx-action@v1
    
    - name: Build
      uses: docker/build-push-action@v2
      with:
        push: false
